version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      network: host
      args:
        - CERTBOT_EMAIL=ilyasudakov@inbox.ru
        - DOMAIN_LIST=194-58-104-192.ovz.vps.regruhosting.ru,www.194-58-104-192.ovz.vps.regruhosting.ru
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - "/node_modules"
      - "./src/static/built:/usr/share/nginx/html/"
      # - letsencrypt:/etc/letsencrypt
