export const defaultPriceItemObject = {
  number: "",
  units: "",
  name: "",
  description: "",
  retailPrice: 0,
  lessThan1500Price: 0,
  lessThan5000Price: 0,
  retailMarketPrice: 0,
  cost: 0,
  dealerPrice: 0,
  distributorPrice: 0,
  partnerPrice: 0,
  stopPrice: 0,
  onSale: false,
  isTopSeller: false,
  isMinimized: true,
};
