export const ltdListDefaultInputObject = {
  name: false,
  legalAddress: false,
  mailingAddress: false,
  phone: false,
  site: false,
  inn: false,
  kpp: false,
  email: false,
  ogrn: false,
  okpo: false,
  okved: false,
  checkingAccount: false,
  bank: false,
  correspondentAccount: false,
  bik: false,
  generalDirector: false,
  accountant: false,
  logo: false,
};