name: CodeClimate Unit/Integration Test Run

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.stories.js'
      - '**.scss'
      - '**.css'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.stories.js'
      - '**.scss'
      - '**.css'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run webpack:prod
      - uses: paambaati/codeclimate-action@v2.7.2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test -- --watchAll=false --coverage
