name: CodeClimate Unit/Integration Test Run

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run start
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: fd9aae5b8192ec345b567c2913292630eaedee1248a920ffa11a00cfcefe8160
        with:
          coverageCommand: npm run test -- --watchAll=false --coverage
