name: GitHub Pages Storybook deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build-storybook --no-dll
      - run: npm run deploy-storybook
      # - name: Deploy storybook to Github Pages
      # uses: deborah-digges/deploy-storybook-action@v14.0
      # with:
      #   access-token: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
