name: CI

on:
  push:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12        
      # Install all dependencies  
      - run: npm i
      # Create folder for generated bundles&files
      - run: npm run mkdir-built
      # Run all test cases 
      - run: npm run test
      # Bundle modules w/ Webpack
      - run: npm run webpack:prod
